# Generated by Django 4.2.30 on 2026-08-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': '1. Personas',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=50)),
                ('personas', models.ManyToManyField(related_name='equipo', to='voley.persona')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': '2. Equipos',
            },
        ),
    ]
